nick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /nick [nickname]'
unnick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /unnick'
nicked-name-prefix-tab: '&7'
nicked-name-prefix-tag: '&7'
nick-chat-format: '&8[&7Player&8] &7%nickname% &8» &f%message%'

#default: earomc - skin
default-skin:
  value: 'ewogICJ0aW1lc3RhbXAiIDogMTY3MDg3OTI4MDk4NywKICAicHJvZmlsZUlkIiA6ICIzMjU3YzMyZjQwMmQ0MTY3YjhhOTk2Njc1ZWY5MDBiNSIsCiAgInByb2ZpbGVOYW1lIiA6ICJlYXJvbWMiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI0OWUyYWIzNGRlNmQyMWY5MjVmZGEzYTgyMTdjYmVlNTBkMmZjNWQxYmMwMTE1NzhiYzNlNzViN2RlNmYyYiIKICAgIH0KICB9Cn0='
  signature: 'NvEg3AHd/dXEXCCmFQanYbtWSU1XFvQzeFn14QF+i1FQLmAdiJCQ41PVhZznvpHj2IjVi/iJrSo6cGQVIiXz3Do8dL+Js0fsfUM/s8AncnuHd4kGS7Z8t4zNSLLFpkRmR8bwGczbgFeYC97785doXJZgH+VBzP3yhCO4nughNs5WeGEk4UOkpaih4GtWRBQ6Tu8zXxXgOKj7W+Xf5mcnCbGHbfMQeGXaQps9vDhfJIjp4/pZqEG4WafeGUKeLbB2VxbFM7193bN1ioB3afUS2Qjx4iIAg1x/fRnteBZIt+ak8P5mKC1m7l9xVy8D4Mz+sVGb9s68Y7eV41W5xdXpjkLvElw5X1Agq9bTLAP2CzwiYjHmkbFk+qwnWckwe1jmOyGwDBUCo1X/k8Q+0cPYK9S3q65yCPJHllH6nrOV5YxYDGtadQ5ELvpKe95a8OWL8gHANQ2GFQLmne4EXajv4rZ12z9MV5/Z5M+wGIq0ntoImynKla8c2ll7ht0FWzdGbu8H6LnL4btnMGZ6vSOm5mxkA9ICsBvCGytBtfHFw2eBWL1zQxMR8FZufAO8nQumnvsf+AIa/ZkclC0Yd7PkeZP8XldGyEvWzBNlTUWkTTS8IeLbiEpeROriQQw2mpKIk5mtvp/GuW3nlDj2abhS6ppGj/nlJiEJNeW4L08qYxM='