nick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /nick [nickname]'
unnick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /unnick'
nicked-name-prefix: '&7'
nick-chat-format: '&8[&7Player&8] &7%nickname% &8» &f%message%'