nick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /nick [nickname]'
unnick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /unnick'
nicked-name-prefix-tab: '&7'
nicked-name-prefix-tag: '&7'
nick-chat-format: '&8[&7Player&8] &7%nickname% &8» &f%message%'

skins:
  - 'ewogICJ0aW1lc3RhbXAiIDogMTY3MDc3ODgxMjAyNywKICAicHJvZmlsZUlkIiA6ICJlN2RiMjA0ZjM5MzY0NTVkYTQ3Njc5NDIyMTI5MjM0OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJQdXJwbGVkZCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hMTZmZjVjYTI5NmJiZGRkNDEyMzkzNTQ3ODVhMTBiZTY4NjIyY2JiNWVhZTg4OGQzMDFkMGM1MjZlOTY5MzIxIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=", "F7ybEEHew/p68NneMXOupP8XqW4OY7HhDyvpYCtlORoyXJ7Fk64wSYsBuqSEQHWhDtsMZfeaUJ3DOVebAhV+a/qw2rZ1Tq0zvRkCMTgPxMDvNJlYT5pBjEngMGX6LUJcRZeaHMlr8UfWqvB8Fn/ruNm0v5N9JRDVOCcY2nWt5zPzCk0Er+/cblwHiuFZYmIeRXaVSWKqfMU3tihsg6myK25rQzEcTyP/MlEDgqG2Pk+3WA/gMghMl3+TcguhttxqTviDXQQaq9O4iv881nmvL1zaluxLxzscIQNG8QAtcZup1U+K5KEeTofH0OcqZjsFa0Vt2kV8UREpUntHG2lkZAyHw41X398VWTRFLnhvm/ej2Nsv6ACmEga3t7Tfy8yX0yTbcApwQOqTYpZFHRIisBflAReJtlr3zegxR8SRWsU+32i4BRFHFdS9FXR5fmCFgifrjkFyO1LgPi31nee50pBbof6WnIT1jPnAymlvPdW7PWfLrh4pbf7U8oCLSZxIGtwHyxtOTc04F2Msac8Lg/0wHBkSA+nby1WUllTfhrmkXmGxngRmBpJJWKgXXYM0KEapgUuK/3sEQgk4MWfYpiI/7rYKGl1Ur9Hni/Lnpodbzi/D2s6svr/t0NzjvoIkYknhOWpwF3ENDCTfZHgwQQxjxvPYwWmvzORsWILEaf0='