nick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /nick [nickname]'
unnick-command:
  permission: 'global.command.nick'
  usage:
    - '&cUsage:'
    - '&c- /unnick'